name: Test & Deploy code when merge to master
run-name: ${{ github.actor }} is testing and deploying new merging code 🚀
on:
  pull_request:
    branches:
     - main
    types: [closed]

jobs:
  cicd-code:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm test
      - name: build app without CI
        run: npm run build
        env:
          CI: false
      - run: npm install -g firebase-tools
      - name: deploy to Firebase
        run: |
          firebase deploy --project movie-guide --token=$FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
